export type ColorType =
  | 'primary'
  | 'green'
  | 'red'
  | 'orange'
  | 'black'
  | 'pink-chilling'
  | 'blue-chilling'
  | 'green-chilling'
  | 'gray'
  | 'darkgreen'
  | 'tangerine'
  | 'russet'
  | 'slateblue'
  | 'coralpink'
  | 'kellygreen'
  | 'siennared'
  | 'skyblue'